### ISSUE TITLE
Please add zil node direct mining

### ISSUE THREAD

**Issue by Canefis** [romslf/Ultimate-Proxy#14]
Hi, please add zil node direct mining

**Comment by romslf** [comment]
Hello **Canefis**,

First, I wanted to take a moment to thank you for reaching out and expressing your interest in a new feature for **Ultimate Proxy**. I appreciate your enthusiasm and support for the project.

I wanted to provide some insight into the current situation regarding feature development for the program. While I'm thrilled to hear your suggestions and ideas, I must admit that my current circumstances require me to focus my efforts on other projects that I have been hired to work on. As much as I enjoy working on **Ultimate Proxy**, unfortunately, it doesn't generate any income for me at the moment.

Please understand that I genuinely value your feedback and suggestions, and I'm grateful to have users like you who appreciate the program. However, in order to sustain myself and continue working on projects like this, I need to allocate my time and resources accordingly.

That being said, I want to assure you that your feature request hasn't gone unnoticed. I have taken note of it and will keep it in mind for future updates when I have the opportunity to work on **Ultimate Proxy** again.

I genuinely appreciate your understanding and patience in this matter. Your continued support means a lot to me, and I hope you will continue to enjoy using the program despite the limitations in implementing new features at the moment.

If you have any other questions or suggestions, please feel free to share them with me. I'm always open to hearing from users like you and appreciate the opportunity to engage with the community.

Thank you once again for your understanding and for being a valued user of **Ultimate Proxy**. Wishing you a fantastic day ahead!

Best regards,
**romslf**
