### ISSUE TITLE
Questions versus issue(s)

### ISSUE THREAD

**Issue by WanderingPhilosopher** [romslf/Ultimate-Proxy#9]
No issues, just questions.

Why are only a few algo/coins supported?
Since code is closed source, I'm not sure how it is working but it seems like a proxy is just a proxy; it sits idle, detects a connection, and auto forwards to a live pool. 
The same question, why do you have listed only x amount of mining software that will work? Again, I can't see the code so I'm not sure.
Why are only certain pools supported?

I have been looking at something like this for awhile but need other algo/coins supported. But my current work around works. I use python and have a script running on all my miners. From my main PC, I type, Pool x, and all the miners change to pool x. It probably takes a little longer to switch via my method but I figure I save money since you are also charging a dev fee. Why lol?! Your software should be open source with no dev fee until all bugs are worked out and it can support unlimited coins and pools. I would like to work with you on this, to test new coins and I would pay you one flat fee if we get it to work, with me having source code with no dev fee.
Awesome program that works within its current limitations. You have achieved what others can't even fathom!

**Comment by Bitofsin** [comment]
hey @WanderingPhilosopher the pools and mining software listed are just verified working ones. other coins and pools might work just fine if they share the algo with the listed coins. I've been talking with the dev and it sounds like there is plans for more coins in the future. there is a discord for the project if you would like quicker reply's than what's possible on here.

**Comment by romslf** [comment]
Hello @WanderingPhilosopher ! 👋
Thank you for your interest in Ultimate Proxy.

> Why are only a few algo/coins supported?

Because almost every algo use a different protocol of communication, even more, sometimes some algo have more than one, Ethash for example: Get Work, Ethproxy, Stratum Nicehash implementation ...

> Since code is closed source, I'm not sure how it is working but it seems like a proxy is just a proxy; it sits idle, detects a connection, and auto forwards to a live pool.

I can see why you would imagine something like this if you think about nginx, but here you are wrong.

Ultimate Proxy is never "idle" but is actively acting and modifying/using request from workers as well as response from pools.
Using Ultimate Proxy, you will only have one connection to the pool acting as one big worker, and every time it receive jobs broadcast it the the connected workers. If receiving shares from workers, then it will send it to the pool configured in config.

If you use the ratio pool switching strategies the proxy will switch from pool to pool without the workers even noticing and therefore with 0 downtime. 

> Why are only certain pools supported?

The list that can be found on the [README.md](https://github.com/romslf/Ultimate-Proxy#readme) is entitled "Non-exhaustive list", which mean some, but not all compatibles services.
But it could be possible that some pools or miners don't work with it if not using the same protocol, as I said before, their is a lot.

> It probably takes a little longer to switch via my method but I figure I save money since you are also charging a dev fee.

Did you accounted for downtime before stating this ? It take a lot of time to restart a miner. What about giving it a try and then decide ? 🙂

> Why lol?!

Because I'm working almost fulltime on it. And this is a part of my company business, which is Pragma Solutions. I also pay for a backend to provide you a unified dashboard statistics. 

> Your software should be open source with no dev fee until all bugs are worked out and it can support unlimited coins and pools. 

I'm currently not searching for contributors and being opensource is not gonna happen for now.  
@Bitofsin which is a user, is actively helping me on his free time to find and fixes all problems. 
I'm also working on a v2 which will allow easier new coins implementations. I rewrite everything from scratch to have the best code base possible.

> I would like to work with you on this, to test new coins and I would pay you one flat fee if we get it to work, with me having source code with no dev fee.

If you want a specific coin to be supported by Ultimate Proxy, then let me know and I will see what I can do.
If you want to be a BETA tester and help me to find problems, then you are welcome !
As for buying the source code or a reduced/removed dev fee version, you can always do a proposition in PM but will likely not happens.

**Comment by WanderingPhilosopher** [comment]
`Did you accounted for downtime before stating this ? It take a lot of time to restart a miner. What about giving it a try and then decide ?`
Yes, I have used mine for forever now, if I were just mining the algos your program works with, maybe yours is better/cheaper even with dev fee, however, my method works with all algos, all pools, and also changes clock and memory settings, which is important. I can go from eth to rvn, on the fly, and change overclocks, by merely typing in a single word.
Do not get me wrong, if your program worked with more/all pools and algos, yours would be better as there is no down time as you said. 

`If you want a specific coin to be supported by Ultimate Proxy, then let me know and I will see what I can do.
If you want to be a BETA tester and help me to find problems, then you are welcome !`
Would it be hard to add kawpow? You have to start looking at the mining world as if ETH is going away via PoS. So where will that hash power go to? another ethash coin, for the asic miners, probably, but what about the GPUs? They will probably leave ethash for etc classic, rvn, or some other algo.
I am happy to help test your program, with different coins and pools. 

`I'm currently not searching for contributors and being opensource is not gonna happen for now.`
Then you need to be more transparent about your dev fee, 1%, but how does it work? 1 minute out of every 100 minutes, etc. Does it tap in to host computer network to divert hash or merely mine on pool where current mining is taking place? Just need to clear up things like that for the public.

**Comment by romslf** [comment]
> all algos, all pools, and also changes clock and memory settings

That's very cool, you could definitely use both depending on what you want to achieve ! 

> Would it be hard to add kawpow?

No, I don't think so, I will look into that 🙂

> You have to start looking at the mining world as if ETH is going away via PoS.

Yes of course, that's why I added TON to the v1 a few days ago. 
But as I said in earlier message, I restarted a new version from scratch to have the best code base possible and to be able to add more coins easily. I'm currently testing it with some users, and we are focused on performances and stability first rather than adding a ton of coins quickly.  But we fixed some problems and the v2 is stable now. So I should be able to add more coins in coming days/weeks.

> Then you need to be more transparent about your dev fee, 1%, but how does it work? 1 minute out of every 100 minutes, etc. Does it tap in to host computer network to divert hash or merely mine on pool where current mining is taking place? Just need to clear up things like that for the public.

I doubt that the average user needs this information, but I will add a little sentence to explain it. 
Mining 36 seconds every hour to a pool using the same crypto that you configured in the config, this way your miners don't need a complete DAG regeneration.
